version: '3'

volumes:
  node_modules:
  postgres:

services:
  db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 25432:5432
